#!/bin/bash

if [ -z "$1" ]; then
	echo "You need atleast one input "
	exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > delete_objects.json

#aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///delete_objects.json
aws s3api delete-objects --bucket $BUCKET_NAME --delete file://delete_objects.json

